# Generated by Django 3.2.6 on 2021-09-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calls', models.IntegerField()),
                ('period', models.IntegerField()),
                ('regex', models.TextField(unique=True)),
            ],
        ),
    ]
