# Generated by Django 3.2.6 on 2021-08-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0002_auto_20210812_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='rate',
        ),
        migrations.AddField(
            model_name='rule',
            name='calls',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='period',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
